import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Noah's Blog",
  description: 'Generated by create next app',
}

export const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image src="/logo.png" alt="logo" width={40} height={40} className='mx-auto' />
        <Link href="/">
        <h1 className="text-2xl text-white font-bold mt-4">Noah's Blog</h1>
        </Link>
        <p className='text-slate-300'>temp text</p>
      </div>
    </header>
)
  
export const footer = (
  <footer className='border-t border-slate-500 mt-12 py-6 text-center text-slate-400'>
    <div>
      <h3>Developed by Noah</h3>
    </div>
  </footer>
)


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}
