import './globals.css'
import { Inter } from 'next/font/google'
import Link from "next/link";
import Image from "next/image";
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Noah's Blog",
  description: 'Generated by create next app',
}

export const header = (
    <header>
      <div className="text-center bg-zinc-700 p-8 my-6 rounded-md">
        <Image src="/fox.png" alt="logo" width={40} height={40} className='mx-auto' />
        <Link href="/">
        <h1 className="text-2xl text-white font-bold mt-4">Noah's Blog</h1>
        </Link>
      </div>
    </header>
)
  
export const footer = (
  <footer className='border-t border-slate-500 mt-12 py-6 text-center content-center text-slate-400'>
    <div>
      <h3>Developed by Noah</h3>
      <div className='justify-center flex flex-row m-2'>
        <Link href="https://www.github.com/noahwhlim" className='mx-3'>
          <Image src="/github.svg" alt="github" width={25} height={25}/>
        </Link>
        <Link href="https://www.linkedin.com/in/noahwhlim">
          <Image src="/linkedin.svg" alt="linkedin" width={25} height={25}/>
        </Link>
      </div>
    </div>
  </footer>
)


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <div className="mx-auto max-w-3xl px-6 grid grid-cols-4">
          <div className='col=span-1 bg-zinc-700 p-8 mt-6 mr-6 rounded-md'>
            <Sidebar />
          </div>
          <div className='col-span-3'>
            {header}
            {children}
          </div>
        </div>
        <div className='mx-auto max-w-2xl px-6'>
            {footer}
          </div> */}
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  )
}
